#pragma once

#include "volk.h"

namespace mvk {
    enum class BorderColor : unsigned int {
        FLOAT_OPAQUE_BLACK = VK_BORDER_COLOR_FLOAT_OPAQUE_BLACK,
        FLOAT_OPAQUE_WHITE = VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE,
        FLOAT_TRANSPARENT_BLACK = VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK,
        INT_OPAQUE_BLACK = VK_BORDER_COLOR_INT_OPAQUE_BLACK,
        INT_OPAQUE_WHITE = VK_BORDER_COLOR_INT_OPAQUE_WHITE,
        INT_TRANSPARENT_BLACK = VK_BORDER_COLOR_INT_TRANSPARENT_BLACK
    };
}
